CREATE TABLE IF NOT EXISTS content_pages (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    slug VARCHAR(190) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    body_html LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    seo_title VARCHAR(255),
    seo_description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS media_assets (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    source_url VARCHAR(1000) NOT NULL,
    storage_key VARCHAR(500) NOT NULL UNIQUE,
    alt_text VARCHAR(500),
    mime_type VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
